import { IActionTypes } from '../_interfaces';

export const creatorConstants: IActionTypes = {
    CREATE_REQUEST: 'CREATOR_CREATE_REQUEST',
    CREATE_SUCCESS: 'CREATOR_CREATE_SUCCESS',
    CREATE_FAILURE: 'CREATOR_CREATE_FAILURE',

    GET_REQUEST: 'CREATOR_GET_REQUEST',
    GET_SUCCESS: 'CREATOR_GET_SUCCESS',
    GET_FAILURE: 'CREATOR_GET_FAILURE',

    GET_BY_ID_REQUEST: 'CREATOR_GET_BY_ID_REQUEST',
    GET_BY_ID_SUCCESS: 'CREATOR_GET_BY_ID_SUCCESS',
    GET_BY_ID_FAILURE: 'CREATOR_GET_BY_ID_FAILURE',

    DELETE_REQUEST: 'CREATOR_DELETE_REQUEST',
    DELETE_SUCCESS: 'CREATOR_DELETE_SUCCESS',
    DELETE_FAILURE: 'CREATOR_DELETE_FAILURE',

    UPDATE_REQUEST: 'CREATOR_UPDATE_REQUEST',
    UPDATE_SUCCESS: 'CREATOR_UPDATE_SUCCESS',
    UPDATE_FAILURE: 'CREATOR_UPDATE_FAILURE'
};
