import { IActionTypes } from '../_interfaces';

export const discConstants: IActionTypes = {
    CREATE_REQUEST: 'DISC_CREATE_REQUEST',
    CREATE_SUCCESS: 'DISC_CREATE_SUCCESS',
    CREATE_FAILURE: 'DISC_CREATE_FAILURE',

    GET_REQUEST: 'DISC_GET_REQUEST',
    GET_SUCCESS: 'DISC_GET_SUCCESS',
    GET_FAILURE: 'DISC_GET_FAILURE',

    GET_BY_ID_REQUEST: 'DISC_GET_BY_ID_REQUEST',
    GET_BY_ID_SUCCESS: 'DISC_GET_BY_ID_SUCCESS',
    GET_BY_ID_FAILURE: 'DISC_GET_BY_ID_FAILURE',

    DELETE_REQUEST: 'DISC_DELETE_REQUEST',
    DELETE_SUCCESS: 'DISC_DELETE_SUCCESS',
    DELETE_FAILURE: 'DISC_DELETE_FAILURE',

    UPDATE_REQUEST: 'DISC_UPDATE_REQUEST',
    UPDATE_SUCCESS: 'DISC_UPDATE_SUCCESS',
    UPDATE_FAILURE: 'DISC_UPDATE_FAILURE'
};
