import { IActionTypes } from '../_interfaces';

export const gameConstants: IActionTypes = {
    CREATE_REQUEST: 'GAME_CREATE_REQUEST',
    CREATE_SUCCESS: 'GAME_CREATE_SUCCESS',
    CREATE_FAILURE: 'GAME_CREATE_FAILURE',

    GET_REQUEST: 'GAME_GET_REQUEST',
    GET_SUCCESS: 'GAME_GET_SUCCESS',
    GET_FAILURE: 'GAME_GET_FAILURE',

    GET_BY_ID_REQUEST: 'GAME_GET_BY_ID_REQUEST',
    GET_BY_ID_SUCCESS: 'GAME_GET_BY_ID_SUCCESS',
    GET_BY_ID_FAILURE: 'GAME_GET_BY_ID_FAILURE',

    DELETE_REQUEST: 'GAME_DELETE_REQUEST',
    DELETE_SUCCESS: 'GAME_DELETE_SUCCESS',
    DELETE_FAILURE: 'GAME_DELETE_FAILURE',

    UPDATE_REQUEST: 'GAME_UPDATE_REQUEST',
    UPDATE_SUCCESS: 'GAME_UPDATE_SUCCESS',
    UPDATE_FAILURE: 'GAME_UPDATE_FAILURE'
};
