import { IActionTypes } from '../_interfaces';

export const bookConstants: IActionTypes = {
    CREATE_REQUEST: 'BOOK_CREATE_REQUEST',
    CREATE_SUCCESS: 'BOOK_CREATE_SUCCESS',
    CREATE_FAILURE: 'BOOK_CREATE_FAILURE',

    GET_REQUEST: 'BOOK_GET_REQUEST',
    GET_SUCCESS: 'BOOK_GET_SUCCESS',
    GET_FAILURE: 'BOOK_GET_FAILURE',

    GET_BY_ID_REQUEST: 'BOOK_GET_BY_ID_REQUEST',
    GET_BY_ID_SUCCESS: 'BOOK_GET_BY_ID_SUCCESS',
    GET_BY_ID_FAILURE: 'BOOK_GET_BY_ID_FAILURE',

    DELETE_REQUEST: 'BOOK_DELETE_REQUEST',
    DELETE_SUCCESS: 'BOOK_DELETE_SUCCESS',
    DELETE_FAILURE: 'BOOK_DELETE_FAILURE',

    UPDATE_REQUEST: 'BOOK_UPDATE_REQUEST',
    UPDATE_SUCCESS: 'BOOK_UPDATE_SUCCESS',
    UPDATE_FAILURE: 'BOOK_UPDATE_FAILURE'
};
