import { IActionTypes } from '../_interfaces';

export const companyConstants: IActionTypes = {
    CREATE_REQUEST: 'COMPANY_CREATE_REQUEST',
    CREATE_SUCCESS: 'COMPANY_CREATE_SUCCESS',
    CREATE_FAILURE: 'COMPANY_CREATE_FAILURE',

    GET_REQUEST: 'COMPANY_GET_REQUEST',
    GET_SUCCESS: 'COMPANY_GET_SUCCESS',
    GET_FAILURE: 'COMPANY_GET_FAILURE',

    GET_BY_ID_REQUEST: 'COMPANY_GET_BY_ID_REQUEST',
    GET_BY_ID_SUCCESS: 'COMPANY_GET_BY_ID_SUCCESS',
    GET_BY_ID_FAILURE: 'COMPANY_GET_BY_ID_FAILURE',

    DELETE_REQUEST: 'COMPANY_DELETE_REQUEST',
    DELETE_SUCCESS: 'COMPANY_DELETE_SUCCESS',
    DELETE_FAILURE: 'COMPANY_DELETE_FAILURE',

    UPDATE_REQUEST: 'COMPANY_UPDATE_REQUEST',
    UPDATE_SUCCESS: 'COMPANY_UPDATE_SUCCESS',
    UPDATE_FAILURE: 'COMPANY_UPDATE_FAILURE'
};
